In [1]:
import numpy as np  # Importing the NumPy library

# Create a NumPy array from a Python list
list_to_array = np.array([1, 2, 3, 4, 5])
print("Array from list:", list_to_array)

Array from list: [1 2 3 4 5]


In [2]:
# Create a NumPy array from a tuple
tuple_to_array = np.array((6, 7, 8, 9, 10))
print("Array from tuple:", tuple_to_array)


Array from tuple: [ 6  7  8  9 10]


In [3]:
type(list_to_array)

numpy.ndarray

In [4]:
 type(tuple_to_array)

numpy.ndarray

In [5]:
# 1D array (vector)
one_dimensional = np.array([1, 2, 3])
print("1D Array:\n", one_dimensional)


1D Array:
 [1 2 3]


In [6]:
# 2D array (matrix)
two_dimensional = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", two_dimensional)


2D Array:
 [[1 2 3]
 [4 5 6]]


In [7]:
# 3D array (tensor)
three_dimensional = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3D Array:\n", three_dimensional)


3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [8]:
# Example array
array_example = np.array([[1, 2, 3], [4, 5, 6]])

# Get the shape of the array (rows, columns)
print("Shape:", array_example.shape)


Shape: (2, 3)


In [9]:
# Get the number of elements in the array
print("Size:", array_example.size)

Size: 6


In [10]:
# Get the data type of the array elements
print("Data type:", array_example.dtype)


Data type: int32


In [11]:
# Get the number of dimensions of the array
print("Number of dimensions:", array_example.ndim)


Number of dimensions: 2


In [12]:
# Get the size of each item in the array (in bytes)
print("Item size:", array_example.itemsize, "bytes")


Item size: 4 bytes


# Exercise

In [13]:
#Question 1
array = np.array([2,4,6,8,10,12])
print(array)

[ 2  4  6  8 10 12]


In [14]:
#Question 2
convert_tuple_to_array = np.array([11,22,33,44,55])
print(convert_tuple_to_array)

[11 22 33 44 55]


In [15]:
#Question 3
new_array = np.arange(10, 16)
print(new_array)

[10 11 12 13 14 15]


In [16]:
#Question 4
two_D_array= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(two_D_array)

print(two_D_array.shape)
print(two_D_array.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9


In [17]:
#Question 5
three_D_array = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(three_D_array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [18]:
#Question 11
array_of_zeros= np.zeros(5)
print(array_of_zeros)

[0. 0. 0. 0. 0.]


In [19]:
#Question 13
array_of_ones = np.ones(7)
print(array_of_ones)

[1. 1. 1. 1. 1. 1. 1.]


In [20]:
#Question 12
matrix_of_zeros= np.zeros((3,3))
print(matrix_of_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
#Question 14
matrix_of_ones= np.ones((4,2))
print(matrix_of_ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [22]:
#Question 15
filled_array= np.full(6,9)
print(filled_array)

[9 9 9 9 9 9]


# Assignment

In [23]:
#Question 6
new_list= np.array([[10, 20], [30, 40], [50, 60]])
print(new_list.shape)
print(new_list.size)
print(new_list.ndim)

(3, 2)
6
2


In [24]:
#Question 7
array= np.array([[1,2],[3,4],[5,6],[7,8]])
print(array.dtype)

int32


In [25]:
#Question 8
first_array= np.arange(1,6)
new_array = np.array(first_array,dtype=float)
print(new_array)
print(new_array.dtype)

[1. 2. 3. 4. 5.]
float64


In [26]:
#Question 9
array2= np.array([[5, 10], [15, 20], [25, 30]])
print(array2.size)
print(array2.ndim)
print(array2.itemsize, "bytes")

6
2
4 bytes


In [36]:
#Question 10
random= np.random.randint(10)
print(random)

7


In [28]:
# Creating two 2D arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Vertical stacking
v_stack = np.vstack((a, b))
print("Vertical Stack:\n", v_stack)

# Horizontal stacking
h_stack = np.hstack((a, b))
print("\nHorizontal Stack:\n", h_stack)


Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]


In [32]:
# Splitting an array into 3 parts along columns
arr = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
split_arr = np.hsplit(arr, 2)
print("\nArray Split into 3 parts:\n", split_arr)



Array Split into 3 parts:
 [array([[1, 2, 3],
       [7, 8, 9]]), array([[ 4,  5,  6],
       [10, 11, 12]])]


In [39]:
# Generate random integers between 0 and 10
random_ints = np.random.randint(0, 10, size=(3, 4))
print("Random Integers:\n", random_ints)

Random Integers:
 [[9 3 7 9]
 [1 3 3 3]
 [2 1 9 5]]


In [51]:
# Generate random floats between 0 and 1
random_floats = 1+np.random.rand(3,3)
print("\nRandom Floats between 0 and 1:\n", random_floats)


Random Floats between 0 and 1:
 [[1.29806806 1.57718045 1.9488398 ]
 [1.84264173 1.34891682 1.9619554 ]
 [1.25603098 1.24903212 1.9082561 ]]


In [52]:
# Generate random numbers from a normal distribution (mean=0, std=1)
random_norm = np.random.normal(0, 1, size=(3, 3))
print("\nRandom Numbers from Normal Distribution:\n", random_norm)



Random Numbers from Normal Distribution:
 [[ 0.01827245 -0.513153   -0.04059013]
 [ 2.34827729 -0.92088989  0.16730996]
 [ 0.29347854 -0.02582188 -1.04759104]]


In [58]:
# Array with NaN and infinite values
data = np.array([1, 2, np.nan, np.inf, -np.inf, 5])

# Check for NaN values
is_nan = np.isnan(data)
print("NaN values in the array:\n", is_nan)

# Check for infinite values
is_inf = np.isinf(data)
print("\nInfinite values in the array:\n", is_inf)

NaN values in the array:
 [False False  True False False False]

Infinite values in the array:
 [False False False  True  True False]


In [57]:
# Replace NaN and infinite values with a specific number (e.g., 0)
cleaned_data = np.where(np.isnan(data) | np.isinf(data), 0, data)
print("\nArray after replacing NaN and inf values with 0:\n", cleaned_data)



Array after replacing NaN and inf values with 0:
 [1. 2. 0. 0. 0. 5.]


# Advanced Numpy Exercise

In [62]:
#Question 1
one_D_array= np.arange(1,16)

two_D_array= one_D_array.reshape(3,5)
three_D_array= one_D_array.reshape(3,1,5)

print("Reshaped to 2D gives:\n", two_D_array)
print("Reshaped to 3D gives:\n", three_D_array)

Reshaped to 2D gives:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Reshaped to 3D gives:
 [[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]

 [[11 12 13 14 15]]]


In [68]:
#Question 2
arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8], 
                [9, 10, 11, 12], 
                [13, 14, 15, 16]])
arr_1d = arr.reshape(-1)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [72]:
#Question 3
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

Vstacked_array= np.vstack((a,b))
print(Vstacked_array)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [73]:
#Question 4
Hstacked_array = np.hstack((a,b))
print(Hstacked_array)

[[1 2 5 6]
 [3 4 7 8]]


In [76]:
#Question 5
two_D= np.ones((2,6))

splitted_array = np.hsplit(two_D,3)
print(splitted_array)

[array([[1., 1.],
       [1., 1.]]), array([[1., 1.],
       [1., 1.]]), array([[1., 1.],
       [1., 1.]])]


In [77]:
#Question 6
random_integers= np.random.randint(10,51,size=(4,4))
print(random_integers)

[[13 43 24 28]
 [21 48 11 24]
 [49 37 30 20]
 [16 20 47 39]]


In [78]:
#Question 7
random_floats= np.random.rand(2,3)
print(random_floats)

[[0.40999551 0.01564431 0.07227774]
 [0.47387599 0.73091057 0.06485199]]


In [79]:
#Question 8
random_normal= np.random.normal(0,2,size=(5,5))
print(random_normal)

[[-1.91142218  1.19877842  1.38928718  0.73275777 -2.84257246]
 [-2.62131177  4.2272363   0.71556519  0.00718943  0.8002693 ]
 [ 1.48867144 -1.94810807 -3.07952561 -0.31847277 -3.18038219]
 [ 3.12619676  4.06597798 -1.94710784  0.15782335  2.14338587]
 [-2.24102955 -3.17128189 -1.36215945 -2.66271372 -0.31670249]]


In [82]:
#Question 9
dataset=np.array([5,10,np.nan,7,np.nan])
isNan= np.isnan(dataset)
print(isNan)

[False False  True False  True]


In [83]:
#Question 10
dataset1=np.array([5,10,np.inf,7,-np.inf])
isInf= np.isinf(dataset1)
print(isInf)

[False False  True False  True]


In [86]:
#Question 11
cleaned_dataset = np.where(np.isnan(dataset), 0, dataset)
print(cleaned_dataset)

[ 5. 10.  0.  7.  0.]


In [89]:
#Question 12
cleaned_dataset1 = np.where(np.isinf(dataset1), 0, dataset1)
print(cleaned_dataset1)

[ 5. 10.  0.  7.  0.]


In [90]:
#Question 13
random_3D= np.random.randint(0,20,size=(4,3,2))
random_3D

array([[[19, 18],
        [ 3,  3],
        [ 3, 15]],

       [[15,  0],
        [ 4, 15],
        [14,  9]],

       [[14, 12],
        [ 2,  5],
        [ 4,  1]],

       [[ 5, 15],
        [ 3,  6],
        [ 8, 13]]])

In [97]:
#Question 14
array= np.array([[1,2,3],[5,3,4],[3,6,5],[4,7,6]])
array.T

array([[1, 5, 3, 4],
       [2, 3, 6, 7],
       [3, 4, 5, 6]])

In [102]:
#Question 15
ran= np.random.randint(1,16,size=(5,5))
print(ran)
diagonal= np.diag(ran)
diagonal

[[ 8  7  8 15 12]
 [14  7  6  3  7]
 [12 13 14  2 12]
 [13 13 10  9  7]
 [14 12  5  3  4]]


array([ 8,  7, 14,  9,  4])